// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vysyx_26010027.h for the primary calling header

#ifndef VERILATED_VYSYX_26010027_YSYX_26010027_H_
#define VERILATED_VYSYX_26010027_YSYX_26010027_H_  // guard

#include "verilated.h"
class Vysyx_26010027_ysyx_26010027_EXU;
class Vysyx_26010027_ysyx_26010027_IDU;
class Vysyx_26010027_ysyx_26010027_IFU;
class Vysyx_26010027_ysyx_26010027_LSU;
class Vysyx_26010027_ysyx_26010027_WBU;
class Vysyx_26010027_ysyx_26010027_icache;


class Vysyx_26010027__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vysyx_26010027_ysyx_26010027 final {
public:
Vysyx_26010027_ysyx_26010027_icache* __PVT__my_icache;
Vysyx_26010027_ysyx_26010027_IFU* __PVT__my_IFU;
Vysyx_26010027_ysyx_26010027_IDU* __PVT__my_IDU;
Vysyx_26010027_ysyx_26010027_EXU* __PVT__my_EXU;
Vysyx_26010027_ysyx_26010027_LSU* __PVT__my_LSU;
Vysyx_26010027_ysyx_26010027_WBU* __PVT__my_WBU;
// Anonymous structures to workaround compiler member-count bugs
struct {
VL_IN8(clock,0,0);
VL_IN8(reset,0,0);
CData/*0:0*/ __PVT__arb_arvalid;
CData/*0:0*/ __PVT__arb_arready;
CData/*3:0*/ __PVT__arb_arid;
CData/*7:0*/ __PVT__arb_arlen;
CData/*2:0*/ __PVT__arb_arsize;
CData/*1:0*/ __PVT__arb_arburst;
CData/*0:0*/ __PVT__arb_rvalid;
CData/*0:0*/ __PVT__arb_rready;
CData/*1:0*/ __PVT__arb_rresp;
CData/*3:0*/ __PVT__arb_rid;
CData/*0:0*/ __PVT__arb_rlast;
CData/*0:0*/ __PVT__arb_awvalid;
CData/*0:0*/ __PVT__arb_awready;
CData/*3:0*/ __PVT__arb_awid;
CData/*7:0*/ __PVT__arb_awlen;
CData/*2:0*/ __PVT__arb_awsize;
CData/*1:0*/ __PVT__arb_awburst;
CData/*0:0*/ __PVT__arb_wvalid;
CData/*0:0*/ __PVT__arb_wready;
CData/*3:0*/ __PVT__arb_wstrb;
CData/*0:0*/ __PVT__arb_wlast;
CData/*0:0*/ __PVT__arb_bvalid;
CData/*0:0*/ __PVT__arb_bready;
CData/*1:0*/ __PVT__arb_bresp;
CData/*3:0*/ __PVT__arb_bid;
CData/*0:0*/ __PVT__pmem_rvalid;
CData/*0:0*/ __PVT__pmem_wready;
CData/*0:0*/ __PVT__pmem_bvalid;
CData/*1:0*/ __PVT__pmem_bresp;
CData/*1:0*/ __PVT__pmem_rresp;
CData/*0:0*/ __PVT__ifu_idu_valid;
CData/*0:0*/ __PVT__idu_ifu_ready;
CData/*0:0*/ __PVT__cpu_ifu_arready;
CData/*0:0*/ __PVT__ifu_cpu_arvalid;
CData/*3:0*/ __PVT__ifu_cpu_arid;
CData/*7:0*/ __PVT__ifu_cpu_arlen;
CData/*2:0*/ __PVT__ifu_cpu_arsize;
CData/*1:0*/ __PVT__ifu_cpu_arburst;
CData/*0:0*/ __PVT__cpu_ifu_rvalid;
CData/*0:0*/ __PVT__ifu_cpu_rready;
CData/*1:0*/ __PVT__cpu_ifu_rresp;
CData/*3:0*/ __PVT__cpu_ifu_rid;
CData/*0:0*/ __PVT__cpu_ifu_rlast;
CData/*0:0*/ __PVT__icache_arvalid;
CData/*0:0*/ __PVT__icache_arready;
CData/*7:0*/ __PVT__icache_arlen;
CData/*3:0*/ __PVT__icache_arid;
CData/*2:0*/ __PVT__icache_arsize;
CData/*1:0*/ __PVT__icache_arburst;
CData/*0:0*/ __PVT__icache_rvalid;
CData/*0:0*/ __PVT__icache_rready;
CData/*1:0*/ __PVT__icache_rresp;
CData/*0:0*/ __PVT__icache_rlast;
CData/*3:0*/ __PVT__icache_rid;
CData/*0:0*/ __PVT__exu_idu_ready;
CData/*0:0*/ __PVT__idu_exu_valid;
CData/*3:0*/ __PVT__idu_exu_alu_op;
CData/*1:0*/ __PVT__idu_exu_mem_w;
CData/*2:0*/ __PVT__idu_exu_mem_r;
CData/*0:0*/ __PVT__idu_exu_alu_arc1;
CData/*0:0*/ __PVT__idu_exu_alu_arc2;
CData/*0:0*/ __PVT__idu_exu_reg_w;
};
struct {
CData/*1:0*/ __PVT__idu_exu_rf_res;
CData/*4:0*/ __PVT__idu_exu_waddr;
CData/*1:0*/ __PVT__idu_exu_jump;
CData/*2:0*/ __PVT__idu_exu_branch;
CData/*0:0*/ __PVT__idu_exu_fencei;
CData/*0:0*/ __PVT__idu_exu_csr_we;
CData/*0:0*/ __PVT__idu_exu_csr_ecall;
CData/*0:0*/ __PVT__idu_exu_csr_mret;
CData/*4:0*/ __PVT__idu_wbu_raddr1;
CData/*4:0*/ __PVT__idu_wbu_raddr2;
CData/*0:0*/ __PVT__lsu_exu_ready;
CData/*0:0*/ __PVT__exu_lsu_valid;
CData/*1:0*/ __PVT__exu_lsu_mem_w;
CData/*2:0*/ __PVT__exu_lsu_mem_r;
CData/*0:0*/ __PVT__exu_lsu_reg_w;
CData/*1:0*/ __PVT__exu_lsu_rf_res;
CData/*4:0*/ __PVT__exu_lsu_waddr;
CData/*0:0*/ __PVT__exu_lsu_csr_we;
CData/*0:0*/ __PVT__exu_lsu_csr_ecall;
CData/*0:0*/ __PVT__exu_lsu_csr_mret;
CData/*0:0*/ __PVT__exu_flush;
CData/*0:0*/ __PVT__wbu_lsu_ready;
CData/*0:0*/ __PVT__lsu_wbu_valid;
CData/*0:0*/ __PVT__lsu_wbu_reg_w;
CData/*1:0*/ __PVT__lsu_wbu_rf_res;
CData/*4:0*/ __PVT__lsu_wbu_waddr;
CData/*0:0*/ __PVT__lsu_load_inflight;
CData/*0:0*/ __PVT__lsu_wbu_csr_we;
CData/*0:0*/ __PVT__lsu_wbu_csr_ecall;
CData/*0:0*/ __PVT__lsu_wbu_csr_mret;
CData/*0:0*/ __PVT__cpu_lsu_arready;
CData/*0:0*/ __PVT__lsu_cpu_arvalid;
CData/*3:0*/ __PVT__lsu_cpu_arid;
CData/*7:0*/ __PVT__lsu_cpu_arlen;
CData/*2:0*/ __PVT__lsu_cpu_arsize;
CData/*1:0*/ __PVT__lsu_cpu_arburst;
CData/*0:0*/ __PVT__cpu_lsu_rvalid;
CData/*0:0*/ __PVT__lsu_cpu_rready;
CData/*1:0*/ __PVT__cpu_lsu_rresp;
CData/*3:0*/ __PVT__cpu_lsu_rid;
CData/*0:0*/ __PVT__cpu_lsu_rlast;
CData/*0:0*/ __PVT__cpu_lsu_awready;
CData/*0:0*/ __PVT__lsu_cpu_awvalid;
CData/*3:0*/ __PVT__lsu_cpu_awid;
CData/*7:0*/ __PVT__lsu_cpu_awlen;
CData/*2:0*/ __PVT__lsu_cpu_awsize;
CData/*1:0*/ __PVT__lsu_cpu_awburst;
CData/*0:0*/ __PVT__cpu_lsu_wready;
CData/*3:0*/ __PVT__lsu_cpu_wstrb;
CData/*0:0*/ __PVT__lsu_cpu_wvalid;
CData/*0:0*/ __PVT__lsu_cpu_wlast;
CData/*0:0*/ __PVT__cpu_lsu_bvalid;
CData/*0:0*/ __PVT__lsu_cpu_bready;
CData/*1:0*/ __PVT__cpu_lsu_bresp;
CData/*3:0*/ __PVT__cpu_lsu_bid;
CData/*1:0*/ __PVT__grant;
CData/*0:0*/ __PVT__handshake_lsu_r;
CData/*0:0*/ __PVT__handshake_lsu_b;
CData/*0:0*/ __PVT__access_fault;
CData/*6:0*/ __PVT__wbu_opcode;
CData/*0:0*/ __PVT__wbu_load;
CData/*0:0*/ __PVT__wbu_store;
CData/*0:0*/ __PVT__wbu_csr;
CData/*0:0*/ __PVT__wbu_jump;
};
struct {
CData/*0:0*/ __PVT__wbu_branch;
CData/*0:0*/ __PVT__wbu_alu;
CData/*0:0*/ __Vdly__pmem_rvalid;
CData/*0:0*/ __Vdly__pmem_wready;
CData/*0:0*/ __Vdly__pmem_bvalid;
CData/*1:0*/ __Vdly__pmem_rresp;
CData/*1:0*/ __Vdly__pmem_bresp;
CData/*1:0*/ __Vdly__grant;
SData/*11:0*/ __PVT__idu_wbu_csr_raddr;
SData/*11:0*/ __PVT__idu_exu_csr_waddr;
SData/*11:0*/ __PVT__exu_lsu_csr_waddr;
SData/*11:0*/ __PVT__lsu_wbu_csr_waddr;
IData/*31:0*/ __PVT__arb_araddr;
IData/*31:0*/ __PVT__arb_rdata;
IData/*31:0*/ __PVT__arb_awaddr;
IData/*31:0*/ __PVT__arb_wdata;
IData/*31:0*/ __PVT__pmem_read_data;
IData/*31:0*/ __PVT__ifu_idu_pc;
IData/*31:0*/ __PVT__ifu_idu_inst;
IData/*31:0*/ __PVT__ifu_cpu_araddr;
IData/*31:0*/ __PVT__cpu_ifu_rdata;
IData/*31:0*/ __PVT__icache_araddr;
IData/*31:0*/ __PVT__icache_rdata;
IData/*31:0*/ __PVT__hit_count;
IData/*31:0*/ __PVT__miss_count;
IData/*31:0*/ __PVT__miss_latency;
IData/*31:0*/ __PVT__idu_exu_pc;
IData/*31:0*/ __PVT__idu_exu_inst;
IData/*31:0*/ __PVT__idu_exu_imm;
IData/*31:0*/ __PVT__idu_exu_target;
IData/*31:0*/ __PVT__exu_lsu_pc;
IData/*31:0*/ __PVT__exu_lsu_snpc;
IData/*31:0*/ __PVT__exu_lsu_inst;
IData/*31:0*/ __PVT__exu_lsu_mem_addr;
IData/*31:0*/ __PVT__exu_lsu_wdata;
IData/*31:0*/ __PVT__exu_lsu_alu_result;
IData/*31:0*/ __PVT__exu_lsu_csr_wdata;
IData/*31:0*/ __PVT__exu_flush_pc;
IData/*31:0*/ __PVT__lsu_wbu_pc;
IData/*31:0*/ __PVT__lsu_wbu_snpc;
IData/*31:0*/ __PVT__lsu_wbu_inst;
IData/*31:0*/ __PVT__lsu_wbu_alu_result;
IData/*31:0*/ __PVT__lsu_wbu_mem_result;
IData/*31:0*/ __PVT__lsu_wbu_csr_wdata;
IData/*31:0*/ __PVT__lsu_cpu_araddr;
IData/*31:0*/ __PVT__cpu_lsu_rdata;
IData/*31:0*/ __PVT__lsu_cpu_awaddr;
IData/*31:0*/ __PVT__lsu_cpu_wdata;
IData/*31:0*/ __PVT__wbu_exu_rdata1;
IData/*31:0*/ __PVT__wbu_exu_rdata2;
IData/*31:0*/ __PVT__wbu_exu_csr_rdata;
IData/*31:0*/ __PVT__wbu_exu_mtvec;
IData/*31:0*/ __PVT__wbu_exu_mepc;
IData/*31:0*/ __Vfunc_pmem_read__0__Vfuncout;
IData/*31:0*/ __Vdly__pmem_read_data;
};
Vysyx_26010027__Syms* vlSymsp;
const char* vlNamep;
Vysyx_26010027_ysyx_26010027() = default;
~Vysyx_26010027_ysyx_26010027() = default;
void ctor(Vysyx_26010027__Syms* symsp, const char* namep);
void dtor();
VL_UNCOPYABLE(Vysyx_26010027_ysyx_26010027);
void __Vconfigure(bool first);
};


#endif  // guard
